"""create_peserta_dan_sumbangan_table

Revision ID: c7adfb38ba4c
Revises: 4a1e18b7fbdc
Create Date: 2025-01-17 16:47:23.391329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c7adfb38ba4c'
down_revision: Union[str, None] = '4a1e18b7fbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peserta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shift', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shift_kebersihan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sumbangan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_peserta', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'id_peserta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sumbangan')
    op.drop_table('peserta')
    # ### end Alembic commands ###
